export const nativeObservationsCopy = {
  en: {
    title: 'Recorded native events', intro: 'Inspect bounded pages from the selected completed native receipt. Selecting a run or platform does not load events.', missing: 'Select “Inspect recorded events” on a completed native run first.', load: 'Load recorded events', next: 'Next page', previous: 'Previous page', refresh: 'Refresh first page', clear: 'Clear observations', platform: 'Recorded platform', pending: 'Loading recorded events…', ready: 'Recorded page validated.', unloaded: 'Events have not been loaded.', empty: 'This platform has no recorded events.', partial: 'Only this page is displayed; counts cover the entire platform log.', stale: 'Previously validated page retained. The latest explicit request failed; these records have not been refreshed.', distinction: 'Counts describe log records, including repeated action information and seed events. They are not unique actions, users, model calls, billed cost or predictions.', bounds: 'At most 20 records per page; 10,000 records per platform; 8 MiB per action log; 8,192 UTF-8 bytes per record. Oversized or malformed evidence is refused without truncation.', run: 'Native run', source: 'Retained source', evidence: 'Receipt evidence SHA-256', range: 'Displayed record indices (zero-based)', total: 'Total recorded log records', event_records: 'Recorded event records', action_records: 'Recorded action records', successful_action_records: 'Recorded successful action records', failed_action_records: 'Recorded failed action records', unknown: 'Other recorded event', literal: 'Original literal JSON', recordHash: 'Record SHA-256', files: 'Validated output manifest', size: 'Bytes',
    errors: { invalid_request: 'The requested page or selected run is invalid.', not_found: 'The owned native run was not found.', unauthorized: 'Authorization expired. Reconnect.', origin_denied: 'The protected connection was denied.', conflict: 'The completed receipt or current source binding could not be confirmed.', tombstoned: 'The source binding is no longer available.', busy: 'The observation reader is busy. Load again explicitly.', result_too_large: 'The evidence or reply exceeds the observation bounds.', observations_unavailable: 'Trusted recorded evidence is unavailable.', evidence_invalid: 'The recorded evidence failed integrity or format checks.', invalid_reply: 'The page did not match the selected receipt, hashes or record contract.', internal_error: 'The reader could not complete this request.', transport_failure: 'The reply was lost. Load again explicitly.', deadline: 'The bounded request timed out. Load again explicitly.', cancelled: 'The observation request was cancelled.', disconnected: 'Reconnect before loading recorded events.' }
  },
  zh: {
    title: '原生事件记录', intro: '查看所选已完成原生凭据的有限分页。选择运行或平台不会加载事件。', missing: '请先在已完成的原生运行上选择“查看记录事件”。', load: '加载记录事件', next: '下一页', previous: '上一页', refresh: '刷新第一页', clear: '清空观察记录', platform: '记录平台', pending: '正在加载记录事件…', ready: '记录分页已验证。', unloaded: '尚未加载事件。', empty: '此平台没有事件记录。', partial: '仅显示当前分页；计数覆盖整个平台日志。', stale: '保留之前已验证的分页。最新手动请求失败，这些记录尚未刷新。', distinction: '计数表示日志记录，包括重复的操作信息及初始事件，并非独立操作、用户、模型调用、账单费用或预测。', bounds: '每页最多20条记录；每个平台最多10,000条；操作日志最多8 MiB；每条记录最多8,192个UTF-8字节。超限或格式错误的证据会被拒绝，不会截断。', run: '原生运行', source: '保留来源', evidence: '凭据证据 SHA-256', range: '显示的记录索引（从零开始）', total: '日志记录总数', event_records: '事件记录数', action_records: '操作记录数', successful_action_records: '成功操作记录数', failed_action_records: '失败操作记录数', unknown: '其他事件记录', literal: '原始字面 JSON', recordHash: '记录 SHA-256', files: '已验证输出清单', size: '字节',
    errors: { invalid_request: '请求分页或所选运行无效。', not_found: '未找到拥有的原生运行。', unauthorized: '授权已过期，请重新连接。', origin_denied: '受保护连接被拒绝。', conflict: '无法确认已完成凭据或当前来源绑定。', tombstoned: '来源绑定已不可用。', busy: '观察读取器正忙，请手动重新加载。', result_too_large: '证据或回复超出观察限制。', observations_unavailable: '可信记录证据不可用。', evidence_invalid: '记录证据未通过完整性或格式检查。', invalid_reply: '分页不符合所选凭据、哈希或记录协议。', internal_error: '读取器无法完成请求。', transport_failure: '回复丢失，请手动重新加载。', deadline: '有限请求超时，请手动重新加载。', cancelled: '观察请求已取消。', disconnected: '加载记录事件前请重新连接。' }
  },
  ms: {
    title: 'Peristiwa asli direkodkan', intro: 'Periksa halaman terhad daripada resit asli selesai yang dipilih. Memilih larian atau platform tidak memuatkan peristiwa.', missing: 'Pilih “Periksa peristiwa direkodkan” pada larian asli selesai dahulu.', load: 'Muatkan peristiwa direkodkan', next: 'Halaman seterusnya', previous: 'Halaman sebelumnya', refresh: 'Segarkan halaman pertama', clear: 'Kosongkan pemerhatian', platform: 'Platform direkodkan', pending: 'Memuatkan peristiwa direkodkan…', ready: 'Halaman rekod disahkan.', unloaded: 'Peristiwa belum dimuatkan.', empty: 'Platform ini tiada peristiwa direkodkan.', partial: 'Hanya halaman ini dipaparkan; kiraan meliputi seluruh log platform.', stale: 'Halaman disahkan terdahulu dikekalkan. Permintaan jelas terkini gagal; rekod ini belum disegarkan.', distinction: 'Kiraan merujuk kepada rekod log, termasuk maklumat tindakan berulang dan peristiwa benih. Ini bukan tindakan unik, pengguna, panggilan model, kos dibilkan atau ramalan.', bounds: 'Maksimum 20 rekod setiap halaman; 10,000 rekod setiap platform; 8 MiB setiap log tindakan; 8,192 bait UTF-8 setiap rekod. Bukti terlalu besar atau rosak ditolak tanpa pemotongan.', run: 'Larian asli', source: 'Sumber tersimpan', evidence: 'SHA-256 bukti resit', range: 'Indeks rekod dipaparkan (bermula sifar)', total: 'Jumlah rekod log direkodkan', event_records: 'Rekod peristiwa direkodkan', action_records: 'Rekod tindakan direkodkan', successful_action_records: 'Rekod tindakan berjaya direkodkan', failed_action_records: 'Rekod tindakan gagal direkodkan', unknown: 'Peristiwa direkodkan lain', literal: 'JSON literal asal', recordHash: 'SHA-256 rekod', files: 'Manifest output disahkan', size: 'Bait',
    errors: { invalid_request: 'Halaman diminta atau larian dipilih tidak sah.', not_found: 'Larian asli dimiliki tidak ditemui.', unauthorized: 'Kebenaran tamat. Sambung semula.', origin_denied: 'Sambungan terlindung ditolak.', conflict: 'Resit selesai atau ikatan sumber semasa tidak dapat disahkan.', tombstoned: 'Ikatan sumber tidak lagi tersedia.', busy: 'Pembaca pemerhatian sibuk. Muatkan semula secara jelas.', result_too_large: 'Bukti atau balasan melebihi had pemerhatian.', observations_unavailable: 'Bukti direkodkan dipercayai tidak tersedia.', evidence_invalid: 'Bukti direkodkan gagal semakan integriti atau format.', invalid_reply: 'Halaman tidak sepadan dengan resit dipilih, hash atau kontrak rekod.', internal_error: 'Pembaca tidak dapat melengkapkan permintaan.', transport_failure: 'Balasan hilang. Muatkan semula secara jelas.', deadline: 'Permintaan terhad tamat masa. Muatkan semula secara jelas.', cancelled: 'Permintaan pemerhatian dibatalkan.', disconnected: 'Sambung semula sebelum memuatkan peristiwa direkodkan.' }
  }
}
export const nativeObservationsCopyFor = locale => nativeObservationsCopy[locale] || nativeObservationsCopy.en
export const nativeObservationsError = (copy, code) => copy.errors[code] || copy.errors.internal_error
