export const nativeLaunchCopy = {
  en: {
    inspect: 'Inspect recorded events',
    reviewPolicy: 'Each new explicit review captures current operator configuration under a new run identity. Previously attempted identities remain available for Refresh; none can be started again.',
    title: 'Native simulation run', intro: 'Review the exact prepared inputs and trusted run limits before explicitly starting the native engine.', missing: 'Complete preparation and refresh its READY receipt first.', review: 'Review native launch', start: 'Start native run', refresh: 'Refresh status', cancel: 'Request cancellation', clear: 'Clear launch view', pending: 'Request in progress…', lost: 'The reply was not confirmed. Refresh this same run; Start cannot be repeated.', changed: 'Prepared input changed. The started run retains its original binding; refresh it explicitly.', disabled: 'Start requires trusted model authorization and a concrete shared-cap reservation.', distinction: 'Prepared inputs are model assumptions grounded in retained source. A native receipt proves observed execution evidence, not a narrative report or a real-world prediction.', reservation: 'The conservative admission ceiling reserves shared spending capacity. It is not billed cost or a provider price guarantee.', closing: 'Clearing or disconnecting this view does not terminate an owned run. Cancellation requests express intent; only native receipts prove a terminal outcome.', project: 'Project', revision: 'Project revision', operation: 'Preparation operation', source: 'Retained source', simulation: 'Prepared simulation', artifact: 'Input artifact SHA-256', run: 'Native run', digest: 'Launch SHA-256', runtime: 'Trusted runtime SHA-256', model: 'Captured model mode', ceiling: 'Admission ceiling (micro-USD)', platforms: 'Platforms', seed: 'Seed', rounds: 'Maximum rounds', calls: 'Maximum model calls', input: 'Maximum input bytes', output: 'Maximum output tokens', seconds: 'Maximum run seconds', requestDigest: 'Native request fingerprint', evidence: 'Native evidence SHA-256', attempt: 'Attempt', instance: 'Owned instance', receipt: 'Validated native receipt', noReceipt: 'No qualified native receipt is available.', cancellation: 'Cancellation requested; termination is not yet proved.', cleanup: 'Owner cleanup', unknown: 'Unknown', pendingCleanup: 'Cleanup pending', observedCleanup: 'No cleanup pending observed', alive: 'Owner thread observed alive', stopped: 'Owner thread observed stopped', workflow: 'Expected workflow', temporal: 'Temporal run', states: { planned: 'Reviewed native plan', queued: 'Queued', starting: 'Starting', running: 'Running', completed: 'Native evidence completed', failed: 'Failed', cancelled: 'Cancelled', uncertain: 'Outcome uncertain' },
    errors: { invalid_request: 'Check the READY preparation binding.', not_found: 'This owned launch was not found.', unauthorized: 'Authorization expired. Reconnect.', origin_denied: 'The protected connection was denied.', conflict: 'The binding changed or Start was already attempted.', busy: 'The native service is busy.', tombstoned: 'The source binding is no longer available.', result_too_large: 'The bounded reply is too large.', model_calls_disabled: 'Trusted model calls are disabled.', budget_denied: 'The shared spending cap denied admission.', native_launch_unavailable: 'Trusted native launch is unavailable.', native_launch_uncertain: 'Launch is uncertain. Refresh; do not restart.', native_launch_failed: 'Native launch failed. Refresh this same run.', invalid_reply: 'The reply did not match the complete native launch contract.', internal_error: 'The native service could not complete this request.', timeout: 'The request timed out. Refresh this same run.', transport_failure: 'The reply was lost. Refresh this same run.' }
  },
  zh: {
    inspect: '查看记录事件',
    reviewPolicy: '每次新的明确审阅都会用新运行标识捕获当前操作员配置。之前尝试过的标识仍可刷新，但不能再次启动。',
    title: '原生模拟运行', intro: '先审阅准确的准备输入及可信运行限制，再明确启动原生引擎。', missing: '请先完成准备，并刷新就绪凭据。', review: '审阅原生启动', start: '启动原生运行', refresh: '刷新状态', cancel: '请求取消', clear: '清空启动视图', pending: '请求进行中…', lost: '回复尚未确认。请刷新同一运行；不能重复启动。', changed: '准备输入已更改。已启动运行保留原绑定，请手动刷新。', disabled: '启动需要可信模型授权和明确的共享额度预留。', distinction: '准备输入是基于保留来源的模型假设。原生凭据证明已观察的执行证据，不代表叙述报告或现实预测。', reservation: '保守准入上限预留共享支出额度，并非账单费用或供应商价格保证。', closing: '清空或断开视图不会终止拥有的运行。取消请求仅表达意图；终止结果须由原生凭据证明。', project: '项目', revision: '项目修订版本', operation: '准备操作', source: '保留来源', simulation: '已准备模拟', artifact: '输入工件 SHA-256', run: '原生运行', digest: '启动 SHA-256', runtime: '可信运行环境 SHA-256', model: '已捕获模型模式', ceiling: '准入上限（微美元）', platforms: '平台', seed: '种子', rounds: '轮数上限', calls: '模型调用上限', input: '输入字节上限', output: '输出令牌上限', seconds: '运行秒数上限', requestDigest: '原生请求指纹', evidence: '原生证据 SHA-256', attempt: '尝试', instance: '拥有的实例', receipt: '已验证原生凭据', noReceipt: '尚无合格原生凭据。', cancellation: '已请求取消；尚未证明已终止。', cleanup: '拥有者清理', unknown: '未知', pendingCleanup: '清理待完成', observedCleanup: '已观察到无待完成清理', alive: '已观察到拥有者线程存活', stopped: '已观察到拥有者线程停止', workflow: '预期工作流', temporal: 'Temporal 运行', states: { planned: '原生计划已审阅', queued: '已排队', starting: '正在启动', running: '正在运行', completed: '原生证据已完成', failed: '失败', cancelled: '已取消', uncertain: '结果不确定' },
    errors: { invalid_request: '请检查就绪准备绑定。', not_found: '未找到拥有的启动。', unauthorized: '授权已过期，请重新连接。', origin_denied: '受保护连接被拒绝。', conflict: '绑定已更改或已尝试启动。', busy: '原生服务正忙。', tombstoned: '来源绑定已不可用。', result_too_large: '回复超出限制。', model_calls_disabled: '可信模型调用已禁用。', budget_denied: '共享支出上限拒绝准入。', native_launch_unavailable: '可信原生启动不可用。', native_launch_uncertain: '启动结果不确定，请刷新，不要重新启动。', native_launch_failed: '原生启动失败，请刷新同一运行。', invalid_reply: '回复不符合完整原生启动协议。', internal_error: '原生服务无法完成请求。', timeout: '请求超时，请刷新同一运行。', transport_failure: '回复丢失，请刷新同一运行。' }
  },
  ms: {
    inspect: 'Periksa peristiwa direkodkan',
    reviewPolicy: 'Setiap semakan baharu yang jelas menangkap konfigurasi pengendali semasa dengan identiti larian baharu. Identiti yang sudah dicuba kekal tersedia untuk Segarkan; tiada yang boleh dimulakan semula.',
    title: 'Larian simulasi asli', intro: 'Semak input disediakan yang tepat dan had larian dipercayai sebelum memulakan enjin asli secara jelas.', missing: 'Lengkapkan penyediaan dan segarkan resit SEDIA dahulu.', review: 'Semak pelancaran asli', start: 'Mulakan larian asli', refresh: 'Segarkan status', cancel: 'Minta pembatalan', clear: 'Kosongkan paparan pelancaran', pending: 'Permintaan sedang diproses…', lost: 'Balasan belum disahkan. Segarkan larian yang sama; Mula tidak boleh diulang.', changed: 'Input disediakan berubah. Larian dimulakan mengekalkan ikatan asal; segarkannya secara jelas.', disabled: 'Mula memerlukan kebenaran model dipercayai dan tempahan had bersama yang konkrit.', distinction: 'Input disediakan ialah andaian model berdasarkan sumber tersimpan. Resit asli membuktikan bukti pelaksanaan yang diperhatikan, bukan laporan naratif atau ramalan dunia sebenar.', reservation: 'Had kemasukan konservatif menempah kapasiti perbelanjaan bersama. Ini bukan kos dibilkan atau jaminan harga pembekal.', closing: 'Mengosongkan atau memutuskan paparan tidak menamatkan larian dimiliki. Permintaan pembatalan menyatakan niat; hanya resit asli membuktikan hasil akhir.', project: 'Projek', revision: 'Semakan projek', operation: 'Operasi penyediaan', source: 'Sumber tersimpan', simulation: 'Simulasi disediakan', artifact: 'SHA-256 artifak input', run: 'Larian asli', digest: 'SHA-256 pelancaran', runtime: 'SHA-256 runtime dipercayai', model: 'Mod model ditangkap', ceiling: 'Had kemasukan (mikro-USD)', platforms: 'Platform', seed: 'Benih', rounds: 'Had pusingan', calls: 'Had panggilan model', input: 'Had bait input', output: 'Had token output', seconds: 'Had saat larian', requestDigest: 'Cap jari permintaan asli', evidence: 'SHA-256 bukti asli', attempt: 'Percubaan', instance: 'Instans dimiliki', receipt: 'Resit asli disahkan', noReceipt: 'Tiada resit asli yang layak tersedia.', cancellation: 'Pembatalan diminta; penamatan belum dibuktikan.', cleanup: 'Pembersihan pemilik', unknown: 'Tidak diketahui', pendingCleanup: 'Pembersihan belum selesai', observedCleanup: 'Tiada pembersihan belum selesai diperhatikan', alive: 'Benang pemilik diperhatikan masih hidup', stopped: 'Benang pemilik diperhatikan berhenti', workflow: 'Aliran kerja dijangka', temporal: 'Larian Temporal', states: { planned: 'Pelan asli disemak', queued: 'Dalam baris gilir', starting: 'Sedang bermula', running: 'Sedang berjalan', completed: 'Bukti asli selesai', failed: 'Gagal', cancelled: 'Dibatalkan', uncertain: 'Hasil tidak pasti' },
    errors: { invalid_request: 'Semak ikatan penyediaan SEDIA.', not_found: 'Pelancaran dimiliki tidak ditemui.', unauthorized: 'Kebenaran tamat. Sambung semula.', origin_denied: 'Sambungan terlindung ditolak.', conflict: 'Ikatan berubah atau Mula sudah dicuba.', busy: 'Perkhidmatan asli sibuk.', tombstoned: 'Ikatan sumber tidak lagi tersedia.', result_too_large: 'Balasan melebihi had.', model_calls_disabled: 'Panggilan model dipercayai dinyahdayakan.', budget_denied: 'Had perbelanjaan bersama menolak kemasukan.', native_launch_unavailable: 'Pelancaran asli dipercayai tidak tersedia.', native_launch_uncertain: 'Pelancaran tidak pasti. Segarkan; jangan mula semula.', native_launch_failed: 'Pelancaran asli gagal. Segarkan larian sama.', invalid_reply: 'Balasan tidak memenuhi kontrak pelancaran asli lengkap.', internal_error: 'Perkhidmatan asli tidak dapat melengkapkan permintaan.', timeout: 'Permintaan tamat masa. Segarkan larian sama.', transport_failure: 'Balasan hilang. Segarkan larian sama.' }
  }
}
export const nativeLaunchCopyFor = locale => nativeLaunchCopy[locale] || nativeLaunchCopy.en
export function nativeLaunchError(copy, code) { return copy.errors[({ deadline: 'timeout', cancelled: 'timeout', disconnected: 'unauthorized' })[code] || code] || copy.errors.internal_error }
