export const populationCopy = {
  en: {
    prepareTwitter: 'Prepare Twitter CSV', prepareReddit: 'Prepare Reddit JSON', saveTwitter: 'Save Twitter CSV', saveReddit: 'Save Reddit JSON', prepared: 'Export prepared and validated. Choose the Save link to request a download.',
    title: 'Population setup', intro: 'Preview typed graph actors as inherited rule-based synthetic profiles.', limits: 'No model enrichment. No simulation executed. This graph projection is not atomic. Type labels and grounding references do not establish real identity or make generated traits source facts.',
    selection: 'Actor selection', types: 'Custom actor types', allTypes: 'Leave all types unchecked to use all admitted custom types. Up to 50 types are shown.', maximum: 'Agent limit (1–100)', seed: 'Seed (0–4294967295)', preview: 'Preview population', twitter: 'Download Twitter CSV', reddit: 'Download Reddit JSON', inspect: 'Inspect profile and grounding', close: 'Close inspector', assumptions: 'Generated assumptions', grounding: 'Original source grounding', summary: 'Node summary', attributes: 'Node attributes', facts: 'Incident source facts', episodes: 'Episode references', evidence: 'Evidence references', labels: 'Node labels', source: 'Source entity UUID', type: 'Producer actor type', individual: 'Individual profile rule', organization: 'Organization profile rule', other: 'Other typed profile rule', traits: 'Show complete synthetic traits', references: 'Show references', previous: 'Previous', next: 'Next', page: 'Page', counts: 'Selected / eligible actors', empty: 'Connect and explicitly preview a population to inspect profiles.', disconnected: 'Connect to the protected graph first.', working: 'Population request in progress.', ready: 'Population preview admitted.', changed: 'Selection changed. Preview again before downloading.', requested: 'Download requested. The browser controls whether the file is saved.', invalid: 'Use whole numbers in the stated ranges and at most 50 admitted custom types.', invalidReply: 'The population response or exported rows did not match the admitted preview.', denied: 'Access denied. Protected population state was cleared.', cancelled: 'Population request cancelled.', unavailable: 'Population export or preview is unavailable on this host.', failed: 'Population request failed. No download was requested.', exportLimit: 'Exports re-read the graph. Matching profile rows does not prove identical source grounding or an atomic snapshot. These files do not configure or run an experiment.', none: 'None', name: 'Name', username: 'Synthetic username', bio: 'Synthetic bio', persona: 'Synthetic persona', date: 'Profile date', outgoing: 'Outgoing', incoming: 'Incoming', edge: 'Edge UUID', endpoints: 'Source → target', fact: 'Complete source fact', integerError: 'Enter a whole number within the stated range.'
  },
  zh: {
    prepareTwitter: '准备 Twitter CSV', prepareReddit: '准备 Reddit JSON', saveTwitter: '保存 Twitter CSV', saveReddit: '保存 Reddit JSON', prepared: '导出已准备并验证。请选择保存链接以请求下载。',
    title: '群体设置', intro: '将图谱中的类型化参与者预览为继承规则生成的合成档案。', limits: '未使用模型增强，也未执行模拟。图谱投影不是原子快照。类型标签和溯源引用不能确定真实身份，也不能使生成特征成为来源事实。',
    selection: '参与者选择', types: '自定义参与者类型', allTypes: '不勾选任何类型时使用所有已接纳的自定义类型。最多显示50种类型。', maximum: '参与者上限（1–100）', seed: '随机种子（0–4294967295）', preview: '预览群体', twitter: '下载 Twitter CSV', reddit: '下载 Reddit JSON', inspect: '查看档案与来源', close: '关闭查看器', assumptions: '生成的假设', grounding: '原始来源依据', summary: '节点摘要', attributes: '节点属性', facts: '关联来源事实', episodes: '片段引用', evidence: '证据引用', labels: '节点标签', source: '来源实体 UUID', type: '生成器参与者类型', individual: '个人档案规则', organization: '机构档案规则', other: '其他类型档案规则', traits: '显示完整合成特征', references: '显示引用', previous: '上一页', next: '下一页', page: '页', counts: '已选择／符合条件的参与者', empty: '连接后明确预览群体，即可查看档案。', disconnected: '请先连接受保护的图谱。', working: '正在请求群体数据。', ready: '群体预览已接纳。', changed: '选择已更改。下载前请重新预览。', requested: '已请求下载。是否保存文件由浏览器决定。', invalid: '请在指定范围内使用整数，并选择不超过50种已接纳的自定义类型。', invalidReply: '群体响应或导出记录与已接纳的预览不一致。', denied: '访问被拒绝。受保护的群体状态已清除。', cancelled: '群体请求已取消。', unavailable: '此主机无法提供群体预览或导出。', failed: '群体请求失败，未请求下载。', exportLimit: '导出会重新读取图谱。档案记录相同不能证明来源依据相同或快照具有原子性。这些文件不会配置或运行实验。', none: '无', name: '名称', username: '合成用户名', bio: '合成简介', persona: '合成人设', date: '档案日期', outgoing: '出向', incoming: '入向', edge: '关系 UUID', endpoints: '来源 → 目标', fact: '完整来源事实', integerError: '请输入指定范围内的整数。'
  },
  ms: {
    prepareTwitter: 'Sediakan CSV Twitter', prepareReddit: 'Sediakan JSON Reddit', saveTwitter: 'Simpan CSV Twitter', saveReddit: 'Simpan JSON Reddit', prepared: 'Eksport disediakan dan disahkan. Pilih pautan Simpan untuk meminta muat turun.',
    title: 'Persediaan populasi', intro: 'Pratonton pelaku graf berjenis sebagai profil sintetik berasaskan peraturan warisan.', limits: 'Tiada pengayaan model. Tiada simulasi dijalankan. Unjuran graf ini bukan petikan atomik. Label jenis dan rujukan sumber tidak membuktikan identiti sebenar atau menjadikan ciri terjana fakta sumber.',
    selection: 'Pemilihan pelaku', types: 'Jenis pelaku tersuai', allTypes: 'Biarkan semua jenis tanpa tanda untuk menggunakan semua jenis tersuai yang diterima. Sehingga 50 jenis dipaparkan.', maximum: 'Had ejen (1–100)', seed: 'Benih (0–4294967295)', preview: 'Pratonton populasi', twitter: 'Muat turun CSV Twitter', reddit: 'Muat turun JSON Reddit', inspect: 'Periksa profil dan sumber', close: 'Tutup pemeriksa', assumptions: 'Andaian terjana', grounding: 'Asas sumber asal', summary: 'Ringkasan nod', attributes: 'Atribut nod', facts: 'Fakta sumber berkaitan', episodes: 'Rujukan episod', evidence: 'Rujukan bukti', labels: 'Label nod', source: 'UUID entiti sumber', type: 'Jenis pelaku pengeluar', individual: 'Peraturan profil individu', organization: 'Peraturan profil organisasi', other: 'Peraturan profil jenis lain', traits: 'Tunjukkan semua ciri sintetik', references: 'Tunjukkan rujukan', previous: 'Sebelumnya', next: 'Seterusnya', page: 'Halaman', counts: 'Pelaku dipilih / layak', empty: 'Sambung dan pratonton populasi secara jelas untuk memeriksa profil.', disconnected: 'Sambung kepada graf terlindung dahulu.', working: 'Permintaan populasi sedang berjalan.', ready: 'Pratonton populasi diterima.', changed: 'Pilihan berubah. Pratonton semula sebelum memuat turun.', requested: 'Muat turun diminta. Pelayar menentukan sama ada fail disimpan.', invalid: 'Gunakan nombor bulat dalam julat yang dinyatakan dan sehingga 50 jenis tersuai yang diterima.', invalidReply: 'Respons populasi atau baris eksport tidak sepadan dengan pratonton yang diterima.', denied: 'Akses ditolak. Keadaan populasi terlindung telah dikosongkan.', cancelled: 'Permintaan populasi dibatalkan.', unavailable: 'Pratonton atau eksport populasi tidak tersedia pada hos ini.', failed: 'Permintaan populasi gagal. Tiada muat turun diminta.', exportLimit: 'Eksport membaca semula graf. Baris profil sepadan tidak membuktikan asas sumber sama atau petikan atomik. Fail ini tidak mengkonfigurasi atau menjalankan eksperimen.', none: 'Tiada', name: 'Nama', username: 'Nama pengguna sintetik', bio: 'Bio sintetik', persona: 'Persona sintetik', date: 'Tarikh profil', outgoing: 'Keluar', incoming: 'Masuk', edge: 'UUID hubungan', endpoints: 'Sumber → sasaran', fact: 'Fakta sumber lengkap', integerError: 'Masukkan nombor bulat dalam julat yang dinyatakan.'
  }
}
export const populationCopyFor = locale => populationCopy[locale] || populationCopy.en
populationCopy.en.emptySelection = 'No typed actors match this selection. Choose other types and preview again.'
populationCopy.zh.emptySelection = '没有类型化参与者符合此选择。请选择其他类型并重新预览。'
populationCopy.ms.emptySelection = 'Tiada pelaku berjenis sepadan dengan pilihan ini. Pilih jenis lain dan pratonton semula.'
export function populationErrorKey(code) {
  if (['unauthorized', 'origin_denied'].includes(code)) return 'denied'
  if (['invalid_request', 'limit_exceeded'].includes(code)) return 'invalid'
  if (['invalid_reply', 'result_too_large'].includes(code)) return 'invalidReply'
  if (['cancelled', 'disconnected'].includes(code)) return 'cancelled'
  if (code === 'empty_selection') return 'emptySelection'
  if (['unsupported', 'not_found', 'population_unavailable'].includes(code)) return 'unavailable'
  return 'failed'
}
