export const preparationCopy = {
  en: {
    reservation: 'The advertised ceiling reserves capacity under the shared spending cap. It is not a billed cost. Start explicitly requests preparation under the trusted operator authorization.',
    title: 'Simulation preparation', intro: 'Review a new source-bound plan, then explicitly schedule rich personas and scenario inputs.', source: 'Retained source', selectSource: 'Inspect an owned retained source in the source library first.', types: 'Actor types (none selected means all)', maximum: 'Maximum actors', seed: 'Native seed', platforms: 'Platforms', rounds: 'Maximum rounds', requirement: 'Simulation requirement', review: 'Review preparation', start: 'Start preparation', refresh: 'Refresh durable status', reset: 'Clear preparation view', actors: 'Selected actors', project: 'Project', revision: 'Project revision', operation: 'Operation', projection: 'Frozen projection SHA-256', digest: 'Plan SHA-256', ceiling: 'Conservative reservation ceiling (micro-USD)', disabled: 'Start is disabled: trusted model authorization and a concrete reservation ceiling are required.', assumptions: 'Rich personas and scenario details are model assumptions. Source references are evidence. Actors are the first eligible UUID-sorted nodes; the seed does not randomize actor selection or promise deterministic model output.', snapshot: 'This is a new frozen review, distinct from the synthetic population preview. The graph scan is not an atomic snapshot.', disconnected: 'Closing or disconnecting this view does not cancel durable preparation.', ready: 'Complete native inputs published. No simulation has executed and no report has been produced.', changed: 'Inputs changed. Review a new plan before Start. The previously started operation remains available for explicit Refresh.', lost: 'The Start reply was not confirmed. Refresh this same operation; do not start a duplicate.', pending: 'Request in progress…', files: 'Published artifact manifest', bytes: 'bytes', artifact: 'Artifact SHA-256', simulation: 'Prepared simulation ID', progress: 'Progress', recovered: 'Status for the previously started operation', states: { planned: 'Reviewed plan', queued: 'Queued', preparing: 'Preparing inputs', ready: 'Inputs ready', failed: 'Preparation failed', cancelled: 'Preparation cancelled', uncertain: 'Outcome uncertain' }, stages: { planned: 'Reviewed', queued: 'Queued', reading: 'Reading frozen source', generating_profiles: 'Generating rich personas', generating_config: 'Generating scenario', publishing: 'Publishing immutable inputs', ready: 'Published', failed: 'Failed', cancelled: 'Cancelled', uncertain: 'Uncertain' },
    errors: { invalid_request: 'Check the selected source and preparation options.', not_found: 'This owned operation or source was not found.', unauthorized: 'Authorization expired. Reconnect.', origin_denied: 'The protected connection was denied.', conflict: 'The plan or project revision changed, or Start was already attempted.', busy: 'The preparation service is busy.', tombstoned: 'This source binding is no longer available.', empty_selection: 'No eligible actors match these types.', result_too_large: 'The bounded preparation result is too large.', preparation_unavailable: 'Trusted preparation is unavailable on this host.', model_calls_disabled: 'Trusted model calls are disabled.', budget_denied: 'The shared spending cap denied the reservation.', preparation_failed: 'Preparation failed; no ready publication is authorized.', preparation_cancelled: 'Durable preparation was cancelled.', preparation_uncertain: 'The outcome is uncertain. Refresh; do not restart.', timeout: 'The request timed out. Refresh a started operation.', transport_failure: 'The reply was lost. Refresh a started operation.', invalid_reply: 'The reply did not match the complete preparation contract.', internal_error: 'The preparation service could not complete this request.' }
  },
  zh: {
    reservation: '显示的上限是在共享支出限制内预留的额度，并非实际账单费用。启动会在可信操作员授权下明确请求准备。',
    title: '模拟准备', intro: '先审阅绑定来源的新计划，再明确启动丰富角色和情景输入的生成。', source: '保留的来源', selectSource: '请先在来源库查看属于此项目的保留来源。', types: '角色类型（不选表示全部）', maximum: '角色数量上限', seed: '原生随机种子', platforms: '平台', rounds: '轮数上限', requirement: '模拟要求', review: '审阅准备计划', start: '启动准备', refresh: '刷新持久状态', reset: '清空准备视图', actors: '已选角色', project: '项目', revision: '项目修订版本', operation: '操作', projection: '冻结图投影 SHA-256', digest: '计划 SHA-256', ceiling: '保守预留上限（微美元）', disabled: '启动已禁用：需要可信模型授权及明确的预留上限。', assumptions: '丰富角色和情景细节是模型假设；来源引用是证据。角色按 UUID 排序选取前面的合格节点；种子不会随机抽取角色，也不保证模型输出可重复。', snapshot: '这是独立于合成群体预览的新冻结计划。图扫描并非原子快照。', disconnected: '关闭或断开此视图不会取消持久准备任务。', ready: '完整原生输入已发布。尚未执行模拟，也未生成报告。', changed: '输入已更改。启动前请审阅新计划。之前启动的操作仍可手动刷新。', lost: '未确认启动回复。请刷新同一操作，不要重复启动。', pending: '请求进行中…', files: '已发布工件清单', bytes: '字节', artifact: '工件 SHA-256', simulation: '已准备的模拟标识', progress: '进度', recovered: '之前启动操作的状态', states: { planned: '计划已审阅', queued: '已排队', preparing: '正在准备输入', ready: '输入已就绪', failed: '准备失败', cancelled: '准备已取消', uncertain: '结果不确定' }, stages: { planned: '已审阅', queued: '已排队', reading: '读取冻结来源', generating_profiles: '生成丰富角色', generating_config: '生成情景', publishing: '发布不可变输入', ready: '已发布', failed: '失败', cancelled: '已取消', uncertain: '不确定' },
    errors: { invalid_request: '请检查来源和准备选项。', not_found: '未找到属于此项目的操作或来源。', unauthorized: '授权已过期，请重新连接。', origin_denied: '受保护连接被拒绝。', conflict: '计划或项目版本已更改，或已尝试启动。', busy: '准备服务正忙。', tombstoned: '此来源绑定已不可用。', empty_selection: '没有符合所选类型的角色。', result_too_large: '准备结果超出限制。', preparation_unavailable: '此主机的可信准备服务不可用。', model_calls_disabled: '可信模型调用已禁用。', budget_denied: '共享支出上限拒绝了预留。', preparation_failed: '准备失败，没有已授权的就绪发布。', preparation_cancelled: '持久准备任务已取消。', preparation_uncertain: '结果不确定，请刷新，不要重新启动。', timeout: '请求超时，请刷新已启动操作。', transport_failure: '回复丢失，请刷新已启动操作。', invalid_reply: '回复不符合完整准备协议。', internal_error: '准备服务无法完成此请求。' }
  },
  ms: {
    reservation: 'Had yang dipaparkan menempah kapasiti di bawah had perbelanjaan bersama. Ini bukan kos yang dibilkan. Mula meminta penyediaan secara jelas di bawah kebenaran pengendali dipercayai.',
    title: 'Penyediaan simulasi', intro: 'Semak pelan baharu yang terikat pada sumber, kemudian jadualkan persona terperinci dan input senario secara jelas.', source: 'Sumber tersimpan', selectSource: 'Periksa sumber tersimpan milik projek dalam pustaka sumber dahulu.', types: 'Jenis pelaku (tiada pilihan bermaksud semua)', maximum: 'Had pelaku', seed: 'Benih asli', platforms: 'Platform', rounds: 'Had pusingan', requirement: 'Keperluan simulasi', review: 'Semak penyediaan', start: 'Mulakan penyediaan', refresh: 'Segarkan status tahan lama', reset: 'Kosongkan paparan penyediaan', actors: 'Pelaku dipilih', project: 'Projek', revision: 'Semakan projek', operation: 'Operasi', projection: 'SHA-256 unjuran beku', digest: 'SHA-256 pelan', ceiling: 'Had tempahan konservatif (mikro-USD)', disabled: 'Mula dinyahdayakan: kebenaran model dipercayai dan had tempahan konkrit diperlukan.', assumptions: 'Persona terperinci dan senario ialah andaian model. Rujukan sumber ialah bukti. Pelaku ialah nod layak pertama mengikut susunan UUID; benih tidak merawakkan pilihan pelaku atau menjamin output model yang sama.', snapshot: 'Ini semakan beku baharu, berasingan daripada pratonton populasi sintetik. Imbasan graf bukan petikan atomik.', disconnected: 'Menutup atau memutuskan paparan ini tidak membatalkan penyediaan tahan lama.', ready: 'Input asli lengkap diterbitkan. Tiada simulasi dilaksanakan dan tiada laporan dihasilkan.', changed: 'Input berubah. Semak pelan baharu sebelum Mula. Operasi terdahulu masih boleh disegarkan secara jelas.', lost: 'Balasan Mula belum disahkan. Segarkan operasi yang sama; jangan mulakan pendua.', pending: 'Permintaan sedang diproses…', files: 'Manifest artifak diterbitkan', bytes: 'bait', artifact: 'SHA-256 artifak', simulation: 'ID simulasi disediakan', progress: 'Kemajuan', recovered: 'Status operasi yang dimulakan sebelum ini', states: { planned: 'Pelan disemak', queued: 'Dalam baris gilir', preparing: 'Menyediakan input', ready: 'Input sedia', failed: 'Penyediaan gagal', cancelled: 'Penyediaan dibatalkan', uncertain: 'Hasil tidak pasti' }, stages: { planned: 'Disemak', queued: 'Dalam baris gilir', reading: 'Membaca sumber beku', generating_profiles: 'Menjana persona terperinci', generating_config: 'Menjana senario', publishing: 'Menerbitkan input kekal', ready: 'Diterbitkan', failed: 'Gagal', cancelled: 'Dibatalkan', uncertain: 'Tidak pasti' },
    errors: { invalid_request: 'Semak sumber dan pilihan penyediaan.', not_found: 'Operasi atau sumber milik projek tidak ditemui.', unauthorized: 'Kebenaran tamat. Sambung semula.', origin_denied: 'Sambungan terlindung ditolak.', conflict: 'Pelan atau semakan projek berubah, atau Mula sudah dicuba.', busy: 'Perkhidmatan penyediaan sibuk.', tombstoned: 'Ikatan sumber ini tidak lagi tersedia.', empty_selection: 'Tiada pelaku layak untuk jenis ini.', result_too_large: 'Hasil penyediaan melebihi had.', preparation_unavailable: 'Penyediaan dipercayai tidak tersedia pada hos ini.', model_calls_disabled: 'Panggilan model dipercayai dinyahdayakan.', budget_denied: 'Had perbelanjaan bersama menolak tempahan.', preparation_failed: 'Penyediaan gagal; tiada penerbitan sedia dibenarkan.', preparation_cancelled: 'Penyediaan tahan lama dibatalkan.', preparation_uncertain: 'Hasil tidak pasti. Segarkan; jangan mulakan semula.', timeout: 'Permintaan tamat masa. Segarkan operasi yang dimulakan.', transport_failure: 'Balasan hilang. Segarkan operasi yang dimulakan.', invalid_reply: 'Balasan tidak memenuhi kontrak penyediaan lengkap.', internal_error: 'Perkhidmatan penyediaan tidak dapat melengkapkan permintaan ini.' }
  }
}
export const preparationCopyFor = locale => preparationCopy[locale] || preparationCopy.en
export function preparationError(copy, code) {
  const normalized = ({ deadline: 'timeout', cancelled: 'timeout', disconnected: 'unauthorized' })[code] || code
  return copy.errors[normalized] || copy.errors.internal_error
}
